NETSTRINGS = {

    # Add here news packs finds

    "ID": "ID_KEY",
    "p": "PING_KEY",
    "ST": "SYNC_TIME_KEY",
    "VChk": "VERSION_CHECK_KEY",
    "OS": "OPERATING_SYSTEM_KEY",
    "OSt": "OPERATING_SYSTEM_TYPE_KEY",
    "VN": "VERSION_NUMBER_KEY",
    "T": "TIME_KEY",
    "STime": "SYNC_TIME_FIELD_KEY",

    "TDmg": "TAKE_DAMAGE_KEY",
    "FKPBl": "FINAL_KILL_PLAYER_BLOCK_KEY",
    "Rez": "REZ_KEY",
    "UD": "UPDATE_DEATH_KEY",

    "DBl": "DAMAGE_BLOCK_KEY",
    "Mp1X": "MAP_POINT1_X_KEY",
    "Mp1Y": "MAP_POINT1_Y_KEY",
    "SSlp": "SYNC_TIME_SERVER_SLEEP_KEY",
    "GPd": "GET_PLAYER_DATA_KEY",
    "Tk": "TOKEN_KEY",
    "CoID": "COGNITO_ID_KEY",
    "U": "PLAYER_ID_KEY",
    "UN": "PLAYER_USERNAME_KEY",
    "pD": "PLAYER_DATA_KEY",
    "Email": "EMAIL_KEY",
    "EmailVerified": "EMAIL_VERIFIED_KEY",
    "RenamePlayer": "RENAME_PLAYER_KEY",
    "S": "SUCCESS_KEY",
    "ER": "ERROR_KEY",
    "MWli": "MENU_WORLD_LOAD_INFO_KEY",
    "WN": "WORLD_NAME_KEY",
    "Ct": "COUNT_KEY",
    "LoginTokenUpdate": "LOGIN_TOKEN_UPDATE_KEY",
    "gLSI": "GET_LIVE_STREAM_INFO_KEY",
    "ULS": "UPDATE_LOCATION_STATUS_KEY",
    "iEC": "INSTRUCTION_EVENT_COMPLETED_KEY",
    "TTjW": "TRY_TO_JOIN_WORLD_KEY",
    "W": "WORLD_KEY",
    "Amt": "AMOUNT_KEY",
    "rUN": "REAL_USERNAME_KEY",
    "BPl": "BAN_PLAYER_KEY",
    "NV": "NEWS_VERSION_KEY",
    "Wo": "WOTW_KEY",
    "WV": "WOTW_VERSION_KEY",
    "WB": "WORLD_BIOME_KEY",
    "JR": "JOIN_RESULT_KEY",
    "Gw": "GET_WORLD_KEY",
    "GWC": "GET_WORLD_COMPRESSED_KEY",
    "eID": "ENTRANCE_PORTAL_ID_KEY",
    "A": "ACHIEVEMENT_KEY",
    "cZL": "CAMERA_ZOOM_LEVEL_UPDATE_KEY",
    "CZL": "CAMERA_ZOOM_LEVEL_UPDATE_FIELD_KEY",
    "cZva": "CAMERA_ZOOM_VALUE_UPDATE_KEY",
    "rOP": "REQUEST_OTHER_PLAYER_KEY",
    "rAI": "REQUEST_AI_ENEMY_KEY",
    "rAIp": "REQUEST_AI_PETS_KEY",
    "GFLi": "GET_FRIEND_LIST_KEY",
    "GSb": "GET_SCOREBOARD_DATA_KEY",
    "WREU": "WORLD_RANDOM_EVENT_UPDATE_KEY",
    "WREgA": "WORLD_RANDOM_EVENT_GET_ALL_ACTIVE_KEY",
    "AnP": "ADD_NETWORK_PLAYER_KEY",

    "t": "TIMESTAMP_KEY",
    "x": "POSITION_X_KEY",
    "y": "POSITION_Y_KEY",
    "PosX": "POSITION_X_FLOAT_KEY",
    "PosY": "POSITION_Y_FLOAT_KEY",
    "a": "ANIMATION_KEY",
    "d": "DIRECTION_KEY",
    "tp": "TELEPORT_KEY",
    "mP": "MY_POSITION_KEY",
    "RtP": "READY_TO_PLAY_KEY",
    "m0": "FIRST_MESSAGE_KEY",

    "TState": "TUTORIAL_STATE_UPDATE_KEY",
    "Tstate": "TUTORIAL_STATE_UPDATE_FIELD_KEY",
    "CharC": "CHARACTER_CREATED_KEY",
    "Gnd": "GENDER_KEY",
    "Ctry": "COUNTRY_KEY",
    "SCI": "SKIN_COLOR_INDEX_KEY",

    "BlockType": "BLOCK_TYPE_KEY",
    "SS": "SET_SEED_KEY",
    "SB": "SET_BLOCK_KEY",
    "SBB": "SET_BLOCK_BACKGROUND_KEY",
    "HB": "HIT_BLOCK_KEY",
    "HBB": "HIT_BLOCK_BACKGROUND_KEY",
    "DB": "DESTROY_BLOCK_KEY",
    "DBBT": "DESTROYED_BLOCK_TYPE_KEY",
    "DSBT": "DESTROYED_SEED_TYPE_KEY",
    "GrowthDuration": "GROWTH_DURATION_KEY",
    "GrowthEndTime": "GROWTH_END_TIME_KEY",
    "Mixed": "IS_MIXED_KEY",

    "HarvestSeeds": "HARVEST_SEEDS_KEY",
    "HarvestBlocks": "HARVEST_BLOCKS_KEY",
    "HarvestGems": "HARVEST_GEMS_KEY",
    "HarvestExtraBlocks": "HARVEST_EXTRA_BLOCKS_KEY",
    "SFe": "SET_FERTILIZER_KEY",
    "C": "COLLECT_KEY",
    "RC": "REMOVE_COLLECT_KEY",

    "CollectableID": "COLLECTABLE_ID_KEY",
    "Amount": "COLLECT_AMOUNT_KEY",
    "InventoryType": "INVENTORY_TYPE_KEY",
    "InventoryData": "INVENTORY_DATA_KEY",
    "IsGem": "IS_GEM_KEY",
    "GemType": "GEM_TYPE_KEY",
    "nCo": "NEW_COLLECTABLE_KEY",

    "BIPack": "BUY_ITEM_PACK_KEY",
    "IPId": "ITEM_PACK_ID_KEY",
    "IPRs": "ITEM_PACK_ROLLS_KEY",
    "IPRs2": "ITEM_PACK_ROLLS2_KEY",
    "LW": "LEAVE_WORLD_KEY",

    "tutorialState": "TUTORIAL_STATE_FIELD_KEY",
    "cameraZoomLevel": "CAMERA_ZOOM_LEVEL_FIELD_KEY",
    "cZv": "CAMERA_ZOOM_VALUE_FIELD_KEY",
    "gems": "GEMS_FIELD_KEY",
    "GAmt": "GEMS_AMOUNT_FIELD_KEY",
    "bcs": "BYTE_COINS_FIELD_KEY",
    "slots": "SLOTS_FIELD_KEY",
    "inv": "INVENTORY_FIELD_KEY",
    "invData": "INVENTORY_DATA_FIELD_KEY",
    "belt1": "BELT1_FIELD_KEY",
    "spots": "SPOTS_FIELD_KEY",

    "fam": "FAMILIAR_BLOCK_TYPE_FIELD_KEY",
    "familiar": "FAMILIAR_BLOCK_TYPE_PLAYER_KEY",
    "pCosT": "PLAYER_COSTUME_FIELD_KEY",
    "pCosET": "PLAYER_COSTUME_END_TIME_FIELD_KEY",
    "famName": "FAMILIAR_NAME_FIELD_KEY",
    "familiarName": "FAMILIAR_NAME_PLAYER_KEY",

    "isFamMaxLvl": "IS_FAMILIAR_MAX_LVL_FIELD_KEY",
    "isFamiliarMaxLevel": "IS_FAMILIAR_MAX_LVL_PLAYER_KEY",

    "faceAnim": "FACE_ANIM_FIELD_KEY",
    "skin": "SKIN_INDEX_FIELD_KEY",
    "gender": "GENDER_FIELD_KEY",
    "Age": "AGE_FIELD_KEY",
    "LvL": "LEVEL_FIELD_KEY",
    "xpLvL": "XP_LEVEL_FIELD_KEY",
    "accountAge": "ACCOUNT_AGE_FIELD_KEY",
    "countryCode": "COUNTRY_CODE_FIELD_KEY",
    "VIPendTime": "VIP_END_TIME_FIELD_KEY",
    "playerAdminStatusKey": "PLAYER_ADMIN_STATUS_FIELD_KEY",
    "starter": "IS_STARTER_FIELD_KEY",
    "IsVIP": "IS_VIP_FIELD_KEY",

    "PL": "PLAYER_LEFT_KEY",
    "WCM": "WORLD_CHAT_MESSAGE_KEY",
    "msg": "MESSAGE_KEY",
    "nick": "NICK_KEY",
    "CmB": "CHAT_MESSAGE_BINARY",
    "userID": "USER_ID_KEY",
    "channel": "CHANNEL_KEY",
    "channelIndex": "CHANNEL_INDEX_KEY",
    "message": "MESSAGE_CHAT_KEY",
    "time": "CHAT_TIME_KEY",
}
